### ISSUE TITLE
Create a Star class

### ISSUE THREAD

**Issue by ghost** [ryanfox/orrery#1]
To a first approximation and for the time being, a Star object in Orrery is represented by only a few key physical parameters:
- stellarMass: the unit of measure is the Sun's mass (i.e. sunMass);
- stellarRadius: the unit of measure is the Sun's radius (i.e. sunRadius);
- stellarLuminosity: the unit of measure is the Sun's luminosity (i.e. sunLuminosity); 

Note: for a star in the main sequence the following is valid (L_star / L_sun) = (M_star / M_sun)^3.9

**Comment by ryanfox** [comment]
Basic star class is created.  We can open new tickets for new functionality.  Closing.
